title: John Lalor
description: Assistant Professor of IT, Analytics, and Operations at Notre Dame
remote_theme: mmistakes/so-simple-theme@3.2.0

repository: jplalor/jplalor.github.io

plugins:
  - jekyll-scholar
  - jekyll-include-cache
  - jekyll-remote-theme

#baseurl: '/'
url: 'https://johnlalor.github.io'

exclude:
  - README.md
  - Gemfile

logo: /images/me.jpg

scholar:
  bibliography_template: bib
  bibtex_filters:
    - latex
